// ============================================================
// Export: Character Card (v2 spec — SillyTavern compatible)
// Creates a CharacterCard v2 JSON file
// ============================================================

import type { ExportData } from "./types";

/**
 * Character Card v2 format used by SillyTavern, TavernAI, etc.
 * Spec: https://github.com/malfoyslastname/character-card-spec-v2
 */
interface CharacterCardV2 {
  spec: "chara_card_v2";
  spec_version: "2.0";
  data: {
    name: string;
    description: string;
    personality: string;
    scenario: string;
    first_mes: string;
    mes_example: string;
    system_prompt: string;
    post_history_instructions: string;
    creator: string;
    creator_notes: string;
    tags: string[];
    character_version: string;
    extensions: Record<string, unknown>;
  };
}

/**
 * Generate a Character Card v2 JSON from soul data.
 * Pure function — no framework imports.
 */
export function exportCharacterCard(data: ExportData): {
  content: string;
  filename: string;
} {
  const slug = data.title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-|-$/g, "");

  // Build example messages in SillyTavern format
  const mesExample = data.sampleConversations
    .map((conversation) =>
      conversation
        .map((msg) => {
          if (msg.role === "user") return `<START>\n{{user}}: ${msg.content}`;
          return `{{char}}: ${msg.content}`;
        })
        .join("\n"),
    )
    .join("\n\n");

  // Extract first message from first conversation if available
  const firstConversation = data.sampleConversations[0];
  const firstAssistantMsg = firstConversation?.find(
    (msg) => msg.role === "assistant",
  );
  const firstMes = firstAssistantMsg?.content ?? "";

  const card: CharacterCardV2 = {
    spec: "chara_card_v2",
    spec_version: "2.0",
    data: {
      name: data.title,
      description: data.soulMd,
      personality: data.tagline || "",
      scenario: "",
      first_mes: firstMes,
      mes_example: mesExample,
      system_prompt: data.systemPrompt,
      post_history_instructions: "",
      creator: "ABTI Soul Generator",
      creator_notes: `Generated by ABTI (AI Brain Type Indicator) — https://abti.me\nMBTI: ${data.mbti}`,
      tags: data.tags,
      character_version: "1.0.0",
      extensions: {
        abti: {
          mbti: data.mbti,
          source: "https://abti.me",
        },
      },
    },
  };

  return {
    content: JSON.stringify(card, null, 2),
    filename: `${slug}-character-card.json`,
  };
}
