// ============================================================
// Export: Claude Skill Package
// Creates a Claude Skills-compatible SKILL.md with embedded README
// ============================================================

import type { ExportData } from "./types";

/**
 * Generate a Claude Skill package as a single downloadable markdown file.
 * The README content is embedded as a comment block at the top.
 * Pure function — no framework imports.
 */
export function exportClaudeSkill(data: ExportData): {
  content: string;
  filename: string;
} {
  const slug = data.title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-|-$/g, "");

  const tagsLine =
    data.tags.length > 0 ? `Tags: ${data.tags.join(", ")}` : "";

  const readmeSection = [
    "<!--",
    `# ${data.title} — Claude Skill`,
    "",
    "## Usage",
    "",
    "1. Copy this file into your project as `.claude/skills/${slug}/SKILL.md`",
    "2. Claude Code will automatically discover and use this skill",
    "3. You can invoke it by referencing the skill name in conversation",
    "",
    "## About",
    "",
    `- **Name**: ${data.title}`,
    `- **MBTI**: ${data.mbti}`,
    data.tagline ? `- **Tagline**: ${data.tagline}` : "",
    tagsLine ? `- **${tagsLine}**` : "",
    "",
    "Generated by ABTI (AI Brain Type Indicator) — https://abti.me",
    "-->",
  ]
    .filter(Boolean)
    .join("\n");

  const skillContent = [
    readmeSection,
    "",
    `# ${data.title}`,
    "",
    data.tagline ? `> ${data.tagline}` : "",
    "",
    data.soulMd,
    "",
    "---",
    "",
    "## System Prompt",
    "",
    data.systemPrompt,
  ]
    .filter((line) => line !== undefined)
    .join("\n");

  return {
    content: skillContent,
    filename: `${slug}-claude-skill.md`,
  };
}
