// ============================================================
// Export: OpenClaw Package
// Creates an OpenClaw-compatible package with embedded claw.json
// ============================================================

import type { ExportData } from "./types";

/**
 * Generate an OpenClaw package as a single downloadable markdown file.
 * The claw.json metadata is embedded as a fenced code block.
 * Pure function — no framework imports.
 */
export function exportOpenClaw(data: ExportData): {
  content: string;
  filename: string;
} {
  const slug = data.title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-|-$/g, "");

  const clawJson = {
    name: data.title,
    description: data.tagline || `${data.title} — ABTI Soul`,
    version: "1.0.0",
    author: "ABTI Soul Generator",
    homepage: "https://abti.me",
    tags: data.tags,
    mbti: data.mbti,
  };

  const content = [
    `# ${data.title} — OpenClaw Package`,
    "",
    data.tagline ? `> ${data.tagline}` : "",
    "",
    "## Metadata (claw.json)",
    "",
    "```json",
    JSON.stringify(clawJson, null, 2),
    "```",
    "",
    "---",
    "",
    "## SKILL.md",
    "",
    data.soulMd,
    "",
    "---",
    "",
    "## System Prompt",
    "",
    data.systemPrompt,
    "",
    "---",
    "",
    "*Generated by [ABTI Soul Generator](https://abti.me)*",
  ]
    .filter((line) => line !== undefined)
    .join("\n");

  return {
    content,
    filename: `${slug}-openclaw.md`,
  };
}
