// ============================================================
// Export: SOUL.md
// Wraps the soul_md content with a proper header and ABTI credit
// ============================================================

/**
 * Generate a downloadable SOUL.md file from soul data.
 * Pure function — no framework imports.
 */
export function exportSoulMd(
  soulMd: string,
  title: string,
): { content: string; filename: string } {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-|-$/g, "");

  const content = [
    `# ${title}`,
    "",
    `> Generated by [ABTI Soul Generator](https://abti.me)`,
    "",
    "---",
    "",
    soulMd,
    "",
    "---",
    "",
    "*This SOUL.md was generated by ABTI (AI Brain Type Indicator).*",
  ].join("\n");

  return {
    content,
    filename: `${slug}-SOUL.md`,
  };
}
